dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "~2.12.0"
- name: "promtail"
  condition: promtail.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "~5.0.0"
- name: "fluent-bit"
  condition: fluent-bit.enabled
  repository: "https://fluent.github.io/helm-charts"
  version: "~0.20.1"
- name: "grafana"
  condition: grafana.enabled
  version: "~6.29.6"
  repository:  "https://grafana.github.io/helm-charts"
- name: "prometheus"
  condition: prometheus.enabled
  version: "~15.9.1"
  repository:  "https://prometheus-community.github.io/helm-charts"
- name: "filebeat"
  condition: filebeat.enabled
  version: "~7.16.3"
  repository:  "https://helm.elastic.co"
- name: "logstash"
  condition: logstash.enabled
  version: "~7.16.3"
  repository:  "https://helm.elastic.co"
