{{ if and .Values.tokengen.enable .Values.enterprise.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "enterprise-logs.tokengenFullname" . }}
  labels:
    {{- include "enterprise-logs.tokengenLabels" . | nindent 4 }}
    {{- with .Values.tokengen.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.tokengen.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    "helm.sh/hook": post-install
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        {{- include "enterprise-logs.tokengenSelectorLabels" . | nindent 8 }}
        {{- with .Values.tokengen.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.tokengen.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.tokengen.priorityClassName }}
      priorityClassName: {{ .Values.tokengen.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.tokengen.securityContext | nindent 8 }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      initContainers:
        - name: loki
          image: {{ template "loki.image" . }}
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          args:
            - -config.file=/etc/loki/config/config.yaml
            - -target=tokengen
            - -tokengen.token-file=/shared/admin-token
            {{- with .Values.tokengen.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if .Values.tokengen.extraVolumeMounts }}
              {{ toYaml .Values.tokengen.extraVolumeMounts | nindent 12 }}
            {{- end }}
            - name: shared
              mountPath: /shared
            - name: config
              mountPath: /etc/loki/config
            - name: license
              mountPath: /etc/loki/license
          env:
            {{- if .Values.tokengen.env }}
              {{ toYaml .Values.tokengen.env | nindent 12 }}
            {{- end }}
      containers:
        - name: create-secret
          image: bitnami/kubectl
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          command:
            - /bin/bash
            - -euc
            - kubectl create secret generic {{ .Values.tokengen.adminTokenSecret }} --from-file=token=/shared/admin-token --from-literal=grafana-token="$(base64 <(echo :$(cat /shared/admin-token)))"
          volumeMounts:
            {{- if .Values.tokengen.extraVolumeMounts }}
              {{ toYaml .Values.tokengen.extraVolumeMounts | nindent 12 }}
            {{- end }}
            - name: shared
              mountPath: /shared
            - name: config
              mountPath: /etc/loki/config
            - name: license
              mountPath: /etc/loki/license
      restartPolicy: OnFailure
      serviceAccount: {{ template "enterprise-logs.tokengenFullname" . }}
      serviceAccountName: {{ template "enterprise-logs.tokengenFullname" . }}
      volumes:
        - name: config
          {{- if .Values.useExternalConfig }}
          secret:
            secretName: {{ .Values.externalConfigName }}
          {{- else }}
          configMap:
            name: {{ include "loki.fullname" . }}
          {{- end }}
        - name: license
          secret:
          {{- if .Values.useExternalLicense }}
            secretName: {{ .Values.externalLicenseName }}
          {{- else }}
            secretName: enterprise-logs-license
          {{- end }}
        - name: shared
          emptyDir: {}
        {{- if .Values.tokengen.extraVolumes }}
        {{ toYaml .Values.tokengen.extraVolumes | nindent 8 }}
        {{- end }}
{{- end }}
